### ISSUE TITLE
Is the project deprecated?

### ISSUE THREAD

**Issue by MarcHe124** [plusglobal/BrowniePHP#39]
I used browniePHP and found it is very flexible.

**Comment by maurozadu** [comment]
yes, the project is not being maintained anymore, you can still use it for CakePHP 2.2.x but it's not being ported to CakePHP 3.

**Comment by jippi** [comment]
CRUD + CRUD-view is still maintained over at FriendsOfCake

**Comment by MarcHe124** [comment]
Thanks, CRUD and CRUD-view are interesting, I will try them on cakephp3.

-- 
Regards,

*He Ma *
